export const storeProducts = [
  {
    id: 1,
    title: "iPhone 8 Plus",
    img: ["img/product-1.png", "img/product-1-2.png"],
    price: 700,
    SegundoPrecio: null,
    model: "iPhone 8 Plus 256 GB",
    info:
      "Capacidad: 256 GB. Bateria: 87%. Accesorios originales de fábrica más una funda transparente y otra original. El celular está Impecable excepto el detalle en el VIDRIO de la cámara de fotos del lado de la que se utiliza para retrato. Ambas cámaras funcionan perfectamente, solo es el vidrio lo que está roto.",
    inCart: false,
    count: 0,
    total: 0,
    usd: true,
    nombre: "",
    whatsapp: "3435054403",
    instagram: "",
  },
  {
    id: 2,
    title: "iPhone 7 Plus",
    img: ["img/product-2.png", "img/product-2-2.png", "img/product-2-3.png"],
    price: 400,
    SegundoPrecio: null,
    model: "iPhone 7 Plus 32GB",
    info:
      "Capacidad: 32 GB. Bateria: 100%. En caja con accesorios, todo original del celular excepto el cable usb que es homologado. Muy buen funcionamiento y buen estado general.    ",
    inCart: false,
    count: 0,
    total: 0,
    usd: true,
    nombre: "",
    whatsapp: "3435135772",
    instagram: "johanagbaron",
  },
  {
    id: 3,
    title: "iPhone 7 Plus",
    img: ["img/product-3.png", "img/product-3-2.png"],
    price: 55000,
    SegundoPrecio: null,
    model: "Rose Gold 32 GB",
    info: "Capacidad: 32 GB. Bateria: 86%. Excelente estado, escucho ofertas!",
    usd: false,
    nombre: "",
    whatsapp: "3424764825",
    instagram: "danihuergook",
  },
  {
    id: 4,
    title: "iPhone 8",
    img: ["img/product-4.png", "img/product-4-2.png", "img/product-4-3.png"],
    price: 500,
    SegundoPrecio: 62000,
    model: "Red 64 GB",
    info:
      "Capacidad: 64GB. Bateria: 86%. En caja con sus accesorios. Impecable estado, sin detalles. Libre de iCloud y empresas. Puedo hacer envios!",
    inCart: false,
    count: 0,
    total: 0,
    usd: true,
    nombre: "",
    whatsapp: "3425978958",
    instagram: "",
  },
  {
    id: 5,
    title: "iPhone 8",
    img: ["img/product-5.png", "img/product-5-2.png", "img/product-5-3.png"],
    price: 500,
    SegundoPrecio: null,
    model: "Space Gray 64 GB",
    info:
      "Capacidad: 64GB. Bateria: 85%. En caja con cargador, manuales, vidrio 9d y funda de regalo. Impecable estado! Acepto iphone menor valor y diferencia! Acepto transferencia en ars/usd, efectivo en ars/usd, mercado pago! Envios a todo el pais!",
    inCart: false,
    count: 0,
    total: 0,
    usd: true,
    nombre: "",
    whatsapp: "3425978958",
    instagram: "cristian_leall",
  },
  {
    id: 6,
    title: "Vintage Iphone",
    img: ["img/product-6.png"],
    price: 17,
    SegundoPrecio: null,
    model: "apple",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    usd: true,
    nombre: "",
    whatsapp: "",
    instagram: "",
  },
  {
    id: 7,
    title: "Iphone 7",
    img: ["img/product-7.png"],
    price: 30,
    SegundoPrecio: null,
    company: "apple",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    usd: true,
    nombre: "",
    whatsapp: "",
    instagram: "",
  },
  {
    id: 8,
    title: "Smashed Iphone",
    img: ["img/product-8.png"],
    price: 2,
    SegundoPrecio: null,
    company: "apple",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    usd: true,
    nombre: "",
    whatsapp: "",
    instagram: "",
  },
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: ["img/product-1.png"],
  price: 10,
  SegundoPrecio: null,
  company: "google",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
  usd: true,
  nombre: "",
  whatsapp: "",
  instagram: "",
};
